SU-SWS/ansible-playbooks

roles/setup-server/templates/drushrc.php

because it breaks new site creations. See https://insight.acquia.com/support/tickets/685034

Remove --extra="-t" from drush sqlq

---

default.migration_vars.yml
roles/add-vhost/tasks/main.yml
roles/change-paths/tasks/main.yml
roles/check-php/tasks/main.yml
roles/css-injector/defaults/main.yml
roles/css-injector/tasks/main.yml
roles/define-paths/tasks/main.yml
roles/setup-site/tasks/main.yml
roles/upload-site/tasks/main.yml

- When we migrate sites to production for testing, we will need to access them at foo.cardinalsites.stanford.edu.  At launch, we'll need to access them at foo.stanford.edu if they have a vhost.  To make sure any absolute paths written during the migration process reflect these two different states, I've added a new launch_tasks variable to specify whether a migration is for launch, and should therefore use the domain foo.stanford.edu.
- Slightly before end of sprint, so we can wrap this work into a release.
- 4
1. Checkout this branch.
2.  Add the launch_tasks variable to your migration_vars.yml file (new example is in default.migration_vars.yml).
2. We'll want to test this with three different runs.  1) on dev with the launch_tasks variable set to empty.  2) on prod with the launch_tasks …

SITES-465: Handle launch and pre-launch paths separately

---

README.md
ansible.cfg
default.migration_vars.yml
group_vars/all.yml
migration-playbook.yml
roles/download-site/tasks/main.yml
roles/upload-site/tasks/main.yml

- Run `drush updb` immediately after restoring the DB
- Provide a method to run a second `drush updb` and ignore errors if a given site has troubles with the database update.
- The sooner this gets merged, the sooner we can merge socorro.
- How critical is this PR on a 1-10 scale? 3
1. Check out `master`
2. Clone https://github.com/SU-SWS/ansible-sync/ into your `ansible-playbooks` directory
3. Create a file in the `inventory` directory called `supri-b` with the following contents:
```
[earth]
supri-b vhost="supri-b"
[depts:children]
earth
[earth:vars]
group_ids=336
```
4. Obtain a Kerberos TGT
5. Run `ansible-playbook -i inventory/supri-b migration-playbook.yml`
6. Weep as you encounter a fatal error "Column not found: 1054 Unknown column 'base.status' in 'field list'"
7. Check out this …

SITES-530: Run drush updb earlier

---

group_vars/depts.yml
group_vars/groups.yml
group_vars/people.yml
group_vars/products.yml
migration-playbook.yml
roles/upload-site/tasks/main.yml

- TL;DR - what's this PR for? Rebuild the registry if our first `drush updb` fails
- How critical is this PR on a 1-10 scale? 6
2. Add `jumpstart-sts vhost="sts"` to an inventory file (the group doesn't matter, you can add it in Earth or GSE from the last testing you did).
3. Clone to `dev`
4. Get a fatal class not defined error
5. Update your inventory entry to be `jumpstart-sts vhost="sts" ignore_updb_errors="TRUE"`
6. Re-run the migration
7. See it fail on the first `drush updb`, ignore the error, and then the second succeeds because we rebuilt the registry.
- Does this PR impact any particular projects, products, or modules? ACSF/Sites 2.0

Add a registry rebuild if drush updb pukes

---

group_vars/all.yml
roles/upload-site/tasks/main.yml

- Disable `acsf_openid` during migration, so that sites that use local Drupal accounts can use them.
- Next week (week of July 16th) should be fine
- How critical is this PR on a 1-10 scale? 2/10
- Affects only one site as far as we know
1. Check out `master`
2. Clone `supri-b` to `dev` or `test`
3. Go to `affiliates/affiliate-program`
4. See no login link in the first sidebar
5. Check out this branch
6. Go to `affiliates/affiliate-program`
7. See the login link in the first sidebar
8. Optionally, create a local Drupal user account with the role "affiliate" and ensure that you can log in and see the affiliate links in the first sidebar
- Does this PR impact any particular projects, products, or modules? ACSF
- JIRA ticket: https://stanfordits.atlassian.net/browse/SITES-225

SITES-225: Block acsf_openid module

---

roles/define-paths/tasks/main.yml
roles/setup-site/tasks/main.yml

- We need the path to the public files directory to do database and CSS Injector surgery. With the current order-of-operations, this variable is empty if the site does not exist yet on ACSF. This PR fixes that.
- Wednesday, August 13.
- How critical is this PR on a 1-10 scale? 4/10 it's causing some issues for HSDO
1. Delete the `religiousstudies` site on `test`
2. Check out this branch
3. Migrate `religious-studies` to `test
4. Verify that you have an image of Tristan at https://religiousstudies-test.cardinalsites.stanford.edu/undergraduate/meet-your-peer-advisor-tristan-navarro
- Does this PR impact any particular projects, products, or modules? ACSF
- JIRA ticket: https://stanfordits.atlassian.net/browse/SITES-823
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad5 …

SITES-823: file_public_path variable is empty if site does not exist on ACSF

---

default.migration_vars.yml
roles/add-vhost/tasks/main.yml
roles/css-injector/tasks/main.yml
roles/define-paths/tasks/main.yml
roles/get-public-files-path/tasks/main.yml
roles/get-sitename/tasks/main.yml
roles/post-db-restore/tasks/main.yml
roles/setup-local/templates/acsf.aliases.drushrc.php
roles/setup-site/tasks/main.yml

- Randomize User 1 password on migration
- Set `debug` statements to output conditionally based on a variable
- Before we do large-scale migrations
- How critical is this PR on a 1-10 scale? 4/10
- Affects every site
1. Set the password of User 1 to a known value on a Sites or people site
2. Migrate it to `test` or `dev`
3. Verify that you *can* log in with `admin/<password>` on ACSF
4. Check out this branch
5. Add `print_debug_messages: "FALSE"` to `migration_vars.yml`
6. Migrate the same site
7. Verify that you can *not* log in with `admin/<password>` on ACSF
8. Re-run the migration and pass `--extra-vars "print_debug_messages=TRUE"` on the command line
9. Verify that debug messages are output (e.g., the `random_pw` variable is output in the "Debug random password" task
- ACSF
- JIRA …

SITES-566: randomize user1 password

---

default.migration_vars.yml
roles/css-injector/tasks/main.yml
roles/define-paths/tasks/main.yml
roles/download-site/tasks/main.yml
roles/post-db-restore/tasks/main.yml

- Eke out some performance gains if AFS is available.
- September 7th?
- Only really applicable to very large sites
- See performance metrics at https://stanfordits.atlassian.net/browse/SITES-723
2. Set `afs_available = "TRUE"` in `migration_vars.yml`
3. Migrate `sws-migration-testing vhost="sws-oddball-vhost"
4. Verify that the images on the homepage copied
5. Verify that the images at `/css` copied and are loading
6. Verify that the images at `/js` copied and are loading
7. Verify that the replacements ran for `admin/config/development/js-injector/list/js_migration_test/edit`
8. Verify that the replacements ran for `admin/config/development/css-injector/edit/2`
- ACSF
- JIRA ticket: …

SITES-723: Create alternate tasks for when AFS is available

---

migration-sync-only-playbook.yml
roles/get-sitename/tasks/main.yml

- Add get-sitename task to sync only so that the site_id variable is available in the clear cache function for css-injector.
- Seems to work without it but the cache clear might fail.
- Low
1. Migrate pulse to production
- ?
- SITES-907

SITES-907: Add missing tasks for css-injector 

---

roles/get-sitename/tasks/main.yml
roles/upload-site/tasks/main.yml

- (Edit the above to reflect status)
- Ensures that all PHP classes are registered to Drupal
- Ensures that all update hooks are found in new & old modules
- Ensures that modules that no longer exist are dropped from the registry as they may have an impact.
- Before migrating Iranian-studies
-  Medium
2. Ensure the dev environment on acsf has the fix for guuid updates in capx.
3. migrate iranian-studies to dev
- SITES-825

SITES-825: Run drush rr immediately after importing the DB.

---

roles/setup-site/tasks/main.yml

- Whenever a site fails to install or if there is a PHP error, the `drush st` check fails to assert that the site exists. When migrating to the ACSF environment we drop the database right away anyhow so no need to bootstrap Drupal. Just check if all the parts are there.
- I run into this all the time testing migrations that already exist that have failed.
- Low
2. Drop the database on iranianstudies dev (drush @acsf.dev.cardinald7.iranianstudies sql-drop)
3. Run full migration playbook using iranian-studies as your inventory item
4. Truncate the `system` table
5. Run `migration-sync-only-playbook.yml`

Check if site exist fails if Drupal has PHP error or database is empty

---

roles/setup-site/tasks/main.yml

- **Update:** See #63 
- In #62, we changed the way that we determined whether a site exists or not from `sites.json`. The conditional to create a new site if it does not exist now is flawed.
- Soonish, although not highly critical because we have all of our "people" sites created on prod already
- How critical is this PR on a 1-10 scale? 4/10
- Affects any sites that we want to create on ACSF that don't already exist.
1. Pick a site to migrate to `dev` or `test`
2. Delete the site on that environment
3. Run `full-migration-playbook.yml` using the `master` branch
4. See that the "Create new site on Site Factory" task is skipped
5. Note that the playbook fails to advance, because there's no site there.
6. Check out this branch.
7. Run `full-migration-playbook.yml`
8. Success
- ACSF
- Other …

Fix logic to create site on ACSF if it does not exist

---

roles/setup-server/templates/.bashrc

- Allows us to track the cache-per-host changes to `~/.bashrc` in this repo, and re-apply that setting if the file gets blown away
- Whenevah
- How critical is this PR on a 1-10 scale? 1/10
1. Delete `~/.bashrc` on a host
2. Run `server-settings-playbook.yml` (LMK if you need an inventory)
3. Verify that the `~./bashrc` looks like this:
```
alias ll='ls -alhF'
WEBHEAD=$(hostname | cut -d'.' -f 1);
export WEBHEAD
CACHE_PREFIX=/home/leland/.drush/$WEBHEAD
export CACHE_PREFIX
```
- ACSF
- JIRA ticket: https://stanfordits.atlassian.net/browse/SITES-965

SITES-965: Add cache-per-host to Ansible setup-server role

---

roles/sites-json/tasks/main.yml

- Bug fix where two sites ending in the same string would get conflated.
- Eh. Soonish.
- Unsure how wide the scope is, but we've already hit conflicts with biology/paleobiology
1. Check out `master`
2. Create two sites on `dev` that end in the same string (e.g., "foo" and "ohzeefoo")
3. Add them to an inventory and run `post-db-restore-playbook.yml` with `print_debug_messages: "TRUE"` (that will let you see the `site_id`)
4. Fail
5. Check out this branch
6. Repeat step 3
7. Rejoice
- ACSF
- JIRA ticket: https://stanfordits.atlassian.net/browse/SITES-980
- Any other contextual information that might be helpful: This rivals the "one pipe" pull request for smallest oversight
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0c …

SITES-980: grep for sites in sites.json is not precise enough

---

acsf-site-setup-playbook.yml
roles/setup-site/tasks/main.yml

- Running `acsf-site-setup-playbook.yml` fails because the `site_id` variable is not populated
- `acsf-site-setup-playbook.yml` needs the `setup-local` role, because it's copying `sites.json` to `/tmp/{{ inventory_hostname }}`
- Early next week?
- It affects `acsf-site-setup-playbook.yml` and `full-migration-playbook.yml`
1. Check out `master`
2. Create an inventory with a site that does not exist `dev` or `test`
3. Run `acsf-site-setup-playbook.yml`
4. See the playbook fail at `add-vhost`
5. Repeat step 2.
6. Run `full-migration-playbook.yml`
7. See the playbook fail at `add-vhost`
8. Check out this branch
9. Repeat steps 2, 3, 5, and 6.
10. Succeed
- Group/dept site migrations
- JIRA ticket: …

SITES-000 and SITES-695

---

acsf-site-setup-playbook.yml
migration-sync-only-playbook.yml

No testing really should be needed here, it just dials down the number of tasks run in serial, and sets `max_fail_percentage=100`. These were the settings I used in creating and syncing the large-scale people and sites migrations.
"Trust me"

SITES-986: Tweaks to site setup and migration sync playbooks

---

group_vars/all.yml
roles/post-db-restore/tasks/main.yml

- Fix file perms
- Before we migrate the next site with file permissions issues
0. Check out `master`
1. `chmod 600 /afs/ir/dist/drupal/ds_sws-migration-testing/files/california-128.png`
2. Sync `sws-migration-testing` to dev
3. Go to https://sws-migration-testing-dev.sites.stanford.edu/file-permissions-test-sites-950
4. See no image
5. Check out this branch
6. Add `chmod: "TRUE"` to your `migration_vars.yml`
7. `chmod 600 /afs/ir/dist/drupal/ds_sws-migration-testing/files/california-128.png`
8. Sync `sws-migration-testing` to dev
9. Go to https://sws-migration-testing-dev.sites.stanford.edu/file-permissions-test-sites-950
10. See image of California flag
1. This requires **both** `afs_available="TRUE"` _and_ a new variable, `chmod="TRUE"` …

SITES-950: chmod to overcome AFS ACLs

---

roles/protect-prod/meta/main.yml
roles/protect-prod/tasks/main.yml

- (Will be ready by 4:35PM PST on 01/07)
- Saves us from having to manually update https://github.com/SU-SWS/ansible-sync/blob/master/prod-sites.yml every time we cut a site over to ACSF
- Prevents blowing away prod sites if their DNS is pointed to ACSF
- The sooner the better
- How critical is this PR on a 1-10 scale? 5/10
- It would have been nice to have this a while ago but better late than never
1. Check out this branch on one of the `people` servers
2. Create this inventory:
```
[groups]
sites734 vhost="sites734"
[groups:vars]
group_ids=206
```
3. Migrate that inventory to **prod** (`acsf_environment: ""`)
4. See that the migration fails with the error message "sites734.stanford.edu  is already pointed to ACSF. You cannot migrate over a production site."
- ACSF migrations
- JIRA …

SITES-734: Protect prod using DNS lookup

---

.gitignore
default.migration_vars.yml
group_vars/all.yml
roles/post-db-restore/tasks/main.yml

- Create an option to rebuild content permissions.
- Yesterday
- How critical is this PR on a 1-10 scale? 5/10
- It affects `migration-sync-only-playbook.yml`, `full-migration-playbook.yml`, and `post-db-restore-playbook.yml`
1. Run a site migration test using the music-dept. Use the `--extra-vars "rebuild_permissions=TRUE"` in your ansible-playbook command. Here's an example: `ansible-playbook -i inventory/minorwm-test full-migration-playbook.yml --extra-vars "rebuild_permissions=TRUE"` 
- Group/dept site migrations
- JIRA ticket: https://stanfordits.atlassian.net/browse/SITES-838
- Anyone who should be notified? ( @jbickar  )

SITES-838: Adding a task to rebuild content permissions

---

roles/post-db-restore/tasks/main.yml

- Enables access to the Site Actions menu for older JS* sites
- Soon would be good.
- Only affects older JS* sites, AFAIK
2. Migrate `jumpstart-argc`, `jumpstart-svndl`, `jumpstart-hsdofinance` and/or `jumpstart-sparq` to dev or test
3. Log in and ensure that you see the Site Actions menu
- Older JS* sites
- JIRA ticket: https://stanfordits.atlassian.net/browse/SITES-1122
- Any other contextual information that might be helpful: on certain sites (e.g., music-dept, public-policy, philosophy), it was necessary to disable `stanford_jumpstart_shortcuts` (which also disables its dependencies), _uninstall_ `stanford_jumpstart_site_actions`, and then _re-enable_ the modules that were disabled (including …

SITES-1122: Disable stanford and stanford_dept profiles for product sites

---

group_vars/all.yml
roles/change-paths/tasks/main.yml

- This runs the script for removing reports menu items from the admin shortcuts menu .
- 01/15/2019
- 7/10
1. Run the full migration using this branch on the dev or test server you used.
2. Go to the `admin/stanford/jumpstart/shortcuts/site-actions` page and make sure the links do not show.
- https://stanfordits.atlassian.net/browse/SITES-952
- Script PR: https://github.com/SU-SWS/acsf-cardinald7/pull/164

SITES-952: Adding the call to the admin-shortcuts.php script

---

roles/post-db-restore/tasks/main.yml

- Change the `files` directory back to 777 on AFS
- We'll need this for SOE department site migrations
1. `chmod 755 /afs/ir/dist/drupal/ds_sws-migration-testing/files`
2. Try to upload a file on https://sws-oddball-vhost.stanford.edu/
3. Fail
4. Migrate `sws-migration-testing vhost="sws-oddball-vhost"` to `dev` or `test`
5. Try to upload a file on https://sws-oddball-vhost.stanford.edu/ and succeed
6. Ensure that `sites/g/files/sbiybj5005321dev/f` is 755
- Does this PR impact any particular projects, products, or modules?
- JIRA ticket: https://stanfordits.atlassian.net/browse/SITES-950
- Other PRs: #78 
- Any other contextual information that might be helpful: see comments in JIRA ticket
- Anyone who should be notified? ( @cjwest )
- [PR …

SITES-950: File permissions

---

roles/add-vhost/tasks/main.yml

- When `launch_tasks="launch"`, sets the Drupal variable of `acsf_helper_canonical_url` to the hostname of the site, only on prod.
- Tuesday, February 5th
- How critical is this PR on a 1-10 scale? 6/10
- We are migrating 90+ sites on Tuesday evening, and I would like to set this for all of them as part of the migration process
2. Migrate the following inventory to `prod`:
```
[groups]
sws-migration-testing vhost="sws-oddball-vhost"
[groups:vars]
group_ids=206
```
3. Go to https://swsmigrationtesting.sites.stanford.edu
4. Get redirected to https://sws-oddball-vhost.stanford.edu/ (that host is still in Sites 1.x; thus you see the potential risks in this approach)
- [JS/JS+ cutovers](https://stanfordits.atlassian.net/browse/SITES-1147)
- JIRA ticket: …

SITES-1190: add task to set acsf_helper_canonical_url at launch

---

roles/post-db-restore/tasks/main.yml

- Recursively `chmod 777` on `sites/default/files`
- 2.7.2019
- We hit permissions errors on the private files directory today on insidesoe
1. `chmod -R /afs/ir/dist/drupal/ds_sws-migration-testing/files/`
2. Check out this branch
3. Migrate `ds_sws-migration-testing`
4. Verify that `/afs/ir/dist/drupal/ds_sws-migration-testing/files/` has 777 perms
- Legacy sites on sites1/sites2
- JIRA ticket: SITES-950
- Other PRs: #78 , #91  
- Any other contextual information that might be helpful: it's OK to do this because AFS ACLs, not Unix permissions, control access
- Anyone who should be notified? ( @cjwest )

SITES-950: chmod subdirectories to 777

---

group_vars/all.yml
playbooks/ace-site-setup-playbook.yml
playbooks/full-migration-playbook.yml
playbooks/migration-sync-only-playbook.yml
roles/add-vhost/meta/main.yml
roles/add-vhost/tasks/main.yml
roles/change-paths/meta/main.yml
roles/change-paths/tasks/main.yml
roles/post-db-restore/meta/main.yml
roles/post-db-restore/tasks/main.yml
roles/protect-prod/meta/main.yml
roles/protect-prod/tasks/main.yml
roles/setup-site/meta/main.yml
roles/upload-site/handlers/main.yml
roles/upload-site/meta/main.yml
roles/upload-site/tasks/main.yml

- Bring us up to feature parity with all of the goodness from the `master` branch
- Before we migrate client sites to StanfordPro
- How critical is this PR on a 1-10 scale? 8/10
- Brings a lot of good stuff
There are a lot of changes in here. Read through the changes with a critical eye. Question anything that looks suspicious and I will give you a test case. I have used this branch for migrating 7 SWS sites to prod, and I tested the `vhost.sites-pro.stanford.edu` with https://cars.sites-pro.stanford.edu.
I'm willing to provide a full set of testing steps for all use cases represented by this change, but that is a level of effort with diminishing returns.
- StanfordPro migrations
- JIRA ticket: SITES-1219
- Other PRs: https://github.com/SU-SWS/ace-stanfordpro/pull/16
- [PR …

SITES-1219: bring in changes from master since this was forked

---

roles/add-vhost/tasks/main.yml

- Fixes error when `vhost.stanford.edu` exists in ACE
- Eh. Soonish? Only affects when we're trying to re-migrate something that's already had its final migraiton.
- How critical is this PR on a 1-10 scale? 2/10
1. Add jsa-content.stanford.edu as a custom domain in ACE
2. Migrate jsa-content to `prod` with `launch_tasks="launch"`
3. Get an error
4. Check out this branch
5. Repeat step 2
6. No error
- StanfordPro migrations
- JIRA ticket: N/A
- Other PRs: N/A

Check whether vhost.stanford.edu has been added in ACE
